### ISSUE TITLE
Animate fish moving

### ISSUE THREAD

**Issue by jaakop** [Fisherman-s-Friends/Fisherman-s-Friends#15]
When the fish moving, set them to use the moving animation that comes with the asset(?)

**Comment by Laffey-chan** [comment]
Created animation for the FishV1. There is 2 deferent animation one fast and one slow


![Image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/d60bd888-ac9d-4c2d-ad8d-a0c0587d7d25)

**Comment by Laffey-chan** [comment]
Created Animation for FishV2. There is 2 Animation slow and fast



![Image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/60899280-4e57-40c6-8a9d-22c57cb073ab)

**Comment by Laffey-chan** [comment]
Created animation's for Fishv3. 2 animation's for slow and fast



![Image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/3017036c-ce0a-42fc-b065-5a80b9bd82d4)

**Comment by Laffey-chan** [comment]
Created animation for FishV4. 2 animation for slow and fast swimming.




![Image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/fba4c7ad-0ef8-4d7e-bb0f-0ccd39db0e57)

**Comment by Laffey-chan** [comment]
Created animation for Shark. 2 animation's for slow and fast.



![Image](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/25053472/364a9c68-d2c8-4574-9aca-8075796c0ead)
