### ISSUE TITLE
Inventory for the fish

### ISSUE THREAD

**Issue by Emiliontti** [Fisherman-s-Friends/Fisherman-s-Friends#16]
A simple inventory system for the collected fish

**Comment by Emiliontti** [comment]
Press button to open inventory, or just a GUI that's on the screen all the time? (or some kind of a point counter system?)

**Comment by jaakop** [comment]
Could the different fish take up different amount of slots? e.g. escape from tarkov or dredge
![kuva](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/0fdf59b1-0bf4-4e74-a4dd-56549595456d)
![kuva](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/8c0c46e6-dc27-43d9-a5b1-70db3d027c55)
