### ISSUE TITLE
Level creation (with assets)

### ISSUE THREAD

**Issue by Emiliontti** [Fisherman-s-Friends/Fisherman-s-Friends#17]
Background/skybox, water plane, ground, foliage etc.

**Comment by jaakop** [comment]
![kuva](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/a0263abf-3618-4e3e-8c29-5e172bb7d368)
Created a simple env. Work in progress. 

Discussed about adding more stuff into the water.

**Comment by jaakop** [comment]
The ground could do with some texture as well?

**Comment by Emiliontti** [comment]
Perspective tweaks (ground vs. water not in level)

**Comment by jaakop** [comment]
![kuva](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/caea3170-c9e4-4a11-87a2-4536ef813c5f)
