### ISSUE TITLE
Finding asset's to use

### ISSUE THREAD

**Issue by Laffey-chan** [Fisherman-s-Friends/Fisherman-s-Friends#8]
Links to asset's for the project if we use any.

**Comment by Laffey-chan** [comment]
[Low Poly Fire](https://assetstore.unity.com/packages/vfx/particles/fire-explosions/low-poly-fire-244190)
[Low Poly Styled Trees](https://assetstore.unity.com/packages/3d/vegetation/trees/low-poly-styled-trees-43103)

**Comment by Emiliontti** [comment]
Fish: https://assetstore.unity.com/packages/3d/characters/animals/fish/fish-polypack-202232
Boat: https://assetstore.unity.com/packages/3d/vehicles/sea/polygrunt-low-poly-boat-177873
Rod: https://assetstore.unity.com/packages/3d/vehicles/sea/boats-polypack-189866
