### ISSUE TITLE
Dialogue

### ISSUE THREAD

**Issue by jaakop** [Fisherman-s-Friends/Fisherman-s-Friends#95]

**Comment by jaakop** [comment]
# Implementation plan
```mermaid
sequenceDiagram
    DialogueTrigger ->>+ Display: Start dialogue
    loop: Until a dialog has no choices:
    loop: Until all lines have been displayed
    Display ->>+ Dialogue: Get next line
    Dialogue ->>- Display: Display the line
    end
    Display ->>+ Dialogue: Get all choices
    Dialogue ->>- Display: Display the choices
    Display ->>+ Choice: Get the new dialog
    Choice ->>- Display: Start the new dialog
    end
```
```mermaid
classDiagram
    Choice --> Actor
    Line --> Actor
    Choice --> Dialogue
    Choice --> Line
    Dialogue --> Choice
    Dialogue --> Line
    DialogueTrigger --> Dialogue
    class Actor{
        +string Name
        +Image Portrait
    }
    class Dialogue{
        +Line[] lines
        +Choice[] choices
    }
    class Line{
        +Actor Speaker
        +string Content
    }
    class Choice{
        +Line line
        +string display
        +Dialogue Response
    }
    class DialogueTrigger {
        +Dialogue
        +Trigger
    }
```

**Comment by jaakop** [comment]
Dialogue, Actor and Choice as Scriptable objects
Choice has a unity event that can be triggered

**Comment by jaakop** [comment]
![kuva](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/7ff57ed4-3150-4f38-8adc-ec0d7365f7b4)

**Comment by Emiliontti** [comment]
Suggestions/Ideas:
- Make so that choices are in the same window, as the asked question
- Connect every line of text to a certain amount of time, that accumulates the longer the dialogue is (1 line, 10 seconds to read or 3 lines 33 seconds to read - the times are fictional btw)
- Have the option to swap the side of the avatar (for example if the shark is telling about the boat, and the avatar blocks the boat, would be better if he was on the other side meanwhile)
- Color coding of "important" words or hints from the text:
"Aha! You just moved here, I see, I see... Well, my name is Garry and I own these lands. Settling here means **_you have to pay a tax_**... yes... let's say it's a tax"

**Comment by jaakop** [comment]
# Implementation
## Process
### Laying the foundation
When I started developing this feature, I first and foremost creted the classes defined in Data structure and then the basic UI elements into a Prefab. Then I programmened the functionality with some basic structure, but not paying special attention to the whole architecture. 
### Applying SOLID
When the dialog was in working order I began to refactor the code with SOLID Principles. First I went through the scripts I created and identified the different responsibilites held in them, so I could later seperate them accroding to the Single responsibility principle. Then I moved all these to their seperate classes and made interfaces for them implementing the rest of the principles on the way. Due to the size of the program I didn't have to worry about the Interface segregation principle since all the interfaces were small by their nature. 
### Cleaning up
When I was ready I made a [pull request](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/pull/99) and started going through code cleaning up variable name methdos and old test code according to the [[CLEAN code]] principles. I also asked a peer-review to see if I had missed anything obvious, but the review didn't find anything
## Product
The final product includes the following
### Dialog editor
Fully integrated custom editor for the dialog objects made with Unity's IMGUI system.
![Pasted image 20231119181603](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/8a6644b2-64a4-4517-aa1e-3795816b96d5)
### Dialog prefab
A ready prefab which can be used as a base to create game specific UIs.
![Pasted image 20231119181733](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/ab560570-89f6-4250-ac9c-31591734fd56)
The prefab has default components attached, but any of these can be replaced with any component that implements the required interface
![Pasted image 20231119181748](https://github.com/Fisherman-s-Friends/Fisherman-s-Friends/assets/10682098/a5f66a21-de71-4daf-bc1c-116150a25565)
The default dialog controller is also safe, as it requires components through Unity's API as well as error messages or handling for missing components. So designers should be able to customize to their liking without mysterious errors or bugs appearing.
```cs
[RequireComponent(
    typeof(IDialogWindowManager),
    typeof(IDialogInput),
    typeof(IWriter))]
public class DialogueController : MonoBehaviour, IDialogueController
{
    private IDialogWindowManager windowManager;
    private IDialogInput input;
    private IWriter writer;
    private ISpeakerController speakerController;
    private IChoiceController choiceController;

    private void Awake()
    {
        if (!TryGetComponent(out windowManager))
        {
            throw new ArgumentNullException("windowManager",
                "Couldn't find IDialogWindowManager attached to the game object");
        }

        if (!TryGetComponent(out input))
        {
            throw new ArgumentNullException("input",
                "Couldn't find IDialogWindowManager attached to the game object");
        }

        if (!TryGetComponent(out writer))
        {
            throw new ArgumentNullException("writer",
                "Couldn't find IWriter attached to the game object");
        }

		// These classes are not required and the component handles them when null
        speakerController = GetComponentInChildren<ISpeakerController>(true);
        choiceController = GetComponentInChildren<IChoiceController>(true);
    }
    /* Rest of the code */
}
```
### Structure
#### Components
```mermaid
classDiagram
direction TB
IDialogController --|> DialogController

DialogController *-- IDialogWindowManager
DialogController *-- IDialogInput
DialogController *-- IWriter
DialogController *-- ISpeakerController
DialogController *-- IChoiceController

ChoiceController *-- IChoiceRenderer

IDialogWindowManager --|> DialogWindowManager
IDialogInput --|> DialogInput
IWriter --|> Writer
ISpeakerController --|> SpeakerController
IChoiceController --|> ChoiceController
IChoiceRenderer --|> ChoiceRenderer

<<interface>> IDialogController
<<interface>> IDialogWindowManager
<<interface>> IDialogInput
<<interface>> IWriter
<<interface>> ISpeakerController
<<interface>> IChoiceController

<<interface>> IChoiceRenderer

class IDialogController {
	+StartDialog(Dialog dialog) : IEnumerator
	+EndDialog()
}
class DialogController {
	+StartDialog(Dialog dialog) : IEnumerator
	+EndDialog()
	-IDialogWindowManager windowManager
	-IDialogInput input
	-IWriter writer
	-ISpeakerController speakerController
	-IChoiceController choiceController
	-ShowLineAndWaitForInput(Line line) : IEnumerator
}
class IDialogWindowManager {
	+ToggleDialogWindow(bool visible)
	+ShowDialogBox()
	+ShowChoicesBox()
}
class DialogWindowManager {
	+ToggleDialogWindow(bool visible)
	+ShowDialogBox()
	+ShowChoicesBox()
	-GameObject box [SerializeField]
	-GameObject dialogueBox [SerializeField]
	-GameObject choiceBox [SerializeField]
}
class IDialogInput {
	+GetInput() : bool
	+WaitForInput() : IEnumerator
}
class DialogInput {
	+GetInput() : bool
	+WaitForInput() : IEnumerator
	-KeyCode[] listenedKeys [SerializeField]
}
class IWriter {
	+SkipLine()
	+WriteByCharacter(string text) : IEnumerator
}
class Writer {
	+SkipLine()
	+WriteByCharacter(string text) : IEnumerator
	-TMP_Text textField [SerializeField]
	-float typingSpeedInSeconds [SerializeField]
	-bool skip
}
class ISpeakerController {
	+UpdateSpeaker(Actor actor)
}
class SpeakerController {
	+UpdateSpeaker(Actor actor)
	-Image speakerImage
}
class IChoiceController {
	+Choice selectedChoice
	+AskChoices(Dialog dialog)
	+WaitForSelection() : IEnumerator
}
class ChoiceController {
	+Choice selectedChoice
	+AskChoices(Dialog dialog)
	+WaitForSelection() : IEnumerator
	-IChoiceRenderer choiceRenderer
}
class IChoiceRenderer {
	+RenderChoices(IEnumerable~Choice~ choices, Action~Choice~ callback)
}
class ChoiceRenderer {
	+RenderChoices(IEnumerable~Choice~ choices, Action~Choice~ callback)
	-Transform choicesHolder[SerializeField]
	-GameObject buttonPrefab[SerializeField]
}
```
#### Data
```mermaid
classDiagram
    Choice --> Actor
    Line --> Actor
    Choice --> Dialogue
    Choice --> Line
    Dialogue --> Choice
    Dialogue --> Line

	<<ScriptableObject>> Actor
	<<ScriptableObject>> Dialogue
	<<ScriptableObject>> Choice

    class Actor{
        +string Name
        +Image Portrait
    }
    class Dialogue{
        +Line[] lines
        +Choice[] choices
    }
    class Line{
        +Actor Speaker
        +string Content
    }
    class Choice{
        +Line line
        +string display
        +Dialogue Response
    }
```
